// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBpB90qS1ATw7MguvnZjEBsUfOfgiAig9A',
    appId: '1:768064793837:web:6d3b04493be1389dce30e4',
    messagingSenderId: '768064793837',
    projectId: 'cryptoapp-aaccb',
    authDomain: 'cryptoapp-aaccb.firebaseapp.com',
    storageBucket: 'cryptoapp-aaccb.firebasestorage.app',
    measurementId: 'G-W9VDHFRJKW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDrPw5ePr3X8rbnaOdmKOOVuyESvYmLikg',
    appId: '1:768064793837:android:91c96ce1bed6d285ce30e4',
    messagingSenderId: '768064793837',
    projectId: 'cryptoapp-aaccb',
    storageBucket: 'cryptoapp-aaccb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA7w7GmAKfV7MDQVI86J1ZROY62BDJWblQ',
    appId: '1:768064793837:ios:efa8d1b33725a18dce30e4',
    messagingSenderId: '768064793837',
    projectId: 'cryptoapp-aaccb',
    storageBucket: 'cryptoapp-aaccb.firebasestorage.app',
    androidClientId: '768064793837-8n3qdilpf5664gmpgonhjl3sfhstq8fd.apps.googleusercontent.com',
    iosClientId: '768064793837-65vbh5b3ka80lvuqg5ggh9nhte9lh702.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoAppNew',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA7w7GmAKfV7MDQVI86J1ZROY62BDJWblQ',
    appId: '1:768064793837:ios:efa8d1b33725a18dce30e4',
    messagingSenderId: '768064793837',
    projectId: 'cryptoapp-aaccb',
    storageBucket: 'cryptoapp-aaccb.firebasestorage.app',
    androidClientId: '768064793837-8n3qdilpf5664gmpgonhjl3sfhstq8fd.apps.googleusercontent.com',
    iosClientId: '768064793837-65vbh5b3ka80lvuqg5ggh9nhte9lh702.apps.googleusercontent.com',
    iosBundleId: 'com.example.cryptoAppNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBpB90qS1ATw7MguvnZjEBsUfOfgiAig9A',
    appId: '1:768064793837:web:e170079209170ff1ce30e4',
    messagingSenderId: '768064793837',
    projectId: 'cryptoapp-aaccb',
    authDomain: 'cryptoapp-aaccb.firebaseapp.com',
    storageBucket: 'cryptoapp-aaccb.firebasestorage.app',
    measurementId: 'G-RDELF859DQ',
  );
}
